config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  root 'users#index'
  get 'signup', to: 'users#new', as: 'signup'
  post 'users/create', to: 'users#create', as: 'users_create'
  get 'posts/new'
  post 'posts/create', to: 'posts#create', as: 'posts_create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :user, class_name: "User", foreign_key: "saito_id"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # has_many :posts
  has_many :posts, class_name: "Post", foreign_key: "saito_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.saito_id = session[:user_id]
    p "============="
    p @post
    p "============="
    if @post.save
      redirect_to root_path
    else
      p "============="
      p @post.errors.full_messages
      p "============="
      render :new
    end
  end

  def index
  end

  private
    def post_params
      params.require(:post).permit(:title)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      p "=========="
      p @user.errors.full_messages
      p "=========="
      render :new
    end
  end
  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lesson3App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul>
    <% if session[:user_id] %>
      <li><a href="/posts/new">投稿</a></li>
      <li>ログアウト</li>
    <% else %>
      <li>会員登録</li>
      <li>ログイン</li>
    <% end %>
  </ul>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>
<%= form_for @post, url: posts_create_path do |f| %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<%= session[:user_id] %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= form_for @user, url: users_create_path do |f| %>
  <%= f.text_field :email %>
  <%= f.text_field :password %>
  <%= f.text_field :password_confirmation %>
  <%= f.submit %>
<% end %>